spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    url: jdbc:postgresql://ticketinguserdb.czuphukdntux.eu-central-1.rds.amazonaws.com:5432/ticketinguserdb
    username: postgres
    password: Cydeo123.
    driver-class-name: org.postgresql.Driver
    initialization-mode: always

server:
  port: 8081

keycloak:
  realm: cydeo-dev
  auth-server-url: http://18.158.59.51:8080/auth
  ssl-required: none
  resource: ticketing-app
  credentials:
    secret: 15odl5SDBmbD1TKM4jlllHkSkerPmq2q
  use-resource-role-mappings: true
  bearer-only: true

master:
  user:
    username: admin
    password: admin
  realm: master
  client: master-client
