spring:
  application:
    name: user-service
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    url: jdbc:postgresql://ticketinguserdb.czuphukdntux.eu-central-1.rds.amazonaws.com:5432/ticketinguserdb
    username: postgres
    password: Cydeo123.
    driver-class-name: org.postgresql.Driver
    initialization-mode: always

server:
  port: 8081

keycloak:
  realm: cydeo-dev
  auth-server-url: http://18.185.103.42:8080/auth
  ssl-required: none
  resource: ticketing-app
  credentials:
    secret: H60klvIQaHbGzOE8yDTDknMp2D1oYBof
  use-resource-role-mappings: true
  bearer-only: true

master:
  user:
    username: admin
    password: admin
  realm: master
  client: master-client

eureka:
  instance:
    preferIpAddress: true
    ipAddress: 3.72.39.193
    status-page-url-path: ${management.context-path}/info
    health-check-url-path: ${management.context-path}/health
  client:
    serviceUrl:
      defaultZone: http://3.72.87.233:8761/eureka/

management:
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: "*"
  context-path: http://3.72.39.193:${server.port}/actuator

feign:
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000
